ds:
  url: 127.0.0.1:3306/gps_traffic
  user: root
  password: 123456
  max-page-size: 1000

logging:
  level:
    io.beetlsql.cli: info

beetl-beetlsql:
  dev: false # 将sql打印到控制台

spring:
  profiles: prod
